FEATURES_PROVIDED += periph_cpuid
FEATURES_PROVIDED += periph_gpio periph_gpio_irq
FEATURES_PROVIDED += periph_pm
FEATURES_PROVIDED += periph_wdt
FEATURES_PROVIDED += periph_rtt
FEATURES_PROVIDED += periph_rtt_32khz


include $(RIOTCPU)/riscv_common/Makefile.features
